### ISSUE TITLE
how to create a frozen graph for image segmentation

### ISSUE THREAD

**Issue by hermitcranecn** [arahusky/Tensorflow-Segmentation#10]
I did trained and inference with this Tensorflow-Segmentation. it worked well. Thanks. 
 So I try to integrate this graph into my application. While I try to freeze this graph with tensorflow python tool freeze_graph, I got the following error. any clue?
 
python3 /path/to/tensorflow/tensorflow/python/tools/freeze_graph.py --input_checkpoint=save/C7,64,2C7,64,1M2C7,64,2C7,64,1M2C7,64,2C7,64,1M2/2017-12-30_090220/model.ckpt-8000 --output_node_names=softmax
2018-01-01 20:41:58.685968: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/home/hermitwang/Projects/tensorflow/tensorflow/python/tools/freeze_graph.py", line 350, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/hermitwang/Projects/tensorflow/tensorflow/python/tools/freeze_graph.py", line 249, in main
    FLAGS.saved_model_tags)
  File "/home/hermitwang/Projects/tensorflow/tensorflow/python/tools/freeze_graph.py", line 239, in freeze_graph
    input_meta_graph_def, input_saved_model_dir, saved_model_tags.split(","))
  File "/home/hermitwang/Projects/tensorflow/tensorflow/python/tools/freeze_graph.py", line 127, in freeze_graph_with_def_protos
    saver = saver_lib.Saver(var_list=var_list)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1251, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by forthtemple** [comment]
Is softmax the correct output node? I thought softmax would be for a standard CNN
