### ISSUE TITLE
Nonetype Inputs and Targets

### ISSUE THREAD

**Issue by csindic** [arahusky/Tensorflow-Segmentation#21]
System: dual 32-core Xeon Gold processors with dual 16GB Nvidia P5000s, 64GB RAM.
tf.__version__==1.8.0; python==3.6.

Issue: Apparent lack of train_targets, train_inputs?
After spending dozens of hours creating pixel-wise ground truths, an attempt to train the model on my own images (which were resized to their respective parent directory denotations), I encountered the following error upon running convolutional_autoencoder.py: 

 `Traceback (most recent call last):
  File "convolutional_autoencoder.py", line 342, in <module>
    train()
  File "convolutional_autoencoder.py", line 220, in train
    inputs, targets = dataset.next_batch()
  File "convolutional_autoencoder.py", line 171, in next_batch
    return np.array(inputs, dtype=np.uint8), np.array(targets, dtype=np.uint8)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by vp1993** [comment]
@csindic did you manage to train it on your own dataset?
